#!/bin/bash

pushd . > /dev/null
SCRIPT_PATH="${BASH_SOURCE[0]}";
if ([ -h "${SCRIPT_PATH}" ]) then
  while([ -h "${SCRIPT_PATH}" ]) do cd `dirname "$SCRIPT_PATH"`; SCRIPT_PATH=`readlink "${SCRIPT_PATH}"`; done
fi
cd `dirname ${SCRIPT_PATH}` > /dev/null
SCRIPT_PATH=`pwd`;
popd  > /dev/null

MZNNJ_DIR=$SCRIPT_PATH

SED='sed -r'
if [[ "$(uname)" == "Darwin" ]]; then
    # The version of sed on Mac has a different option to enable extended regular expressions
    SED='sed -E'
fi

param1=${*##*.dzn}
param=${param1##*.mzn}
problem=`echo "$*" | $SED 's/ -.*//'`
mzn2fzn -I ${MZNNJ_DIR}/mznlib --output-to-stdout $problem | ${MZNNJ_DIR}/fzn_numberjack - $param
