x1 = 1;
x2 = false;
x3 = false;
x4 = false;
----------
x1 = 1;
x2 = false;
x3 = true;
x4 = false;
----------
x1 = 1;
x2 = true;
x3 = false;
x4 = true;
----------
x1 = 1;
x2 = true;
x3 = true;
x4 = true;
----------
x1 = 2;
x2 = false;
x3 = false;
x4 = false;
----------
x1 = 2;
x2 = false;
x3 = true;
x4 = true;
----------
x1 = 2;
x2 = true;
x3 = false;
x4 = false;
----------
x1 = 2;
x2 = true;
x3 = true;
x4 = true;
----------
==========
